# -*- coding: utf-8 -*-
"""ClasseNotafiscal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sSbUapNulYWjrAJFYbw5JsvFdsOL67DF
"""

from datetime import datetime,date
from random import randint

class NotaFiscal():

  def __init__(self,codigo,recebimento,valor,tipo,descricao):
    self.__codigo=codigo
    self.__recebimento=recebimento
    self.__valor=valor
    self.__tipo=tipo
    self.__descricao=descricao

  def bloquear_modificacao(self, nome):
      raise ValueError(f"Não é possível modificar o {nome} do boleto.")

  @property
  def codigo(self):
    return self.__codigo
  @codigo.setter
  def codigo(self, alteracao):
    raise ValueError(self.bloquear_modificacao("código"))

  @property
  def recebimento(self):
    return self.__vencimento
  @recebimento.setter
  def recebimento(self, alteracao):
    raise ValueError(self.bloquear_modificacao("recebimento"))

  @property
  def valor(self):
    return self.__valor
  @valor.setter
  def valor(self, alteracao):
    raise ValueError(self.bloquear_modificacao("valor"))

  @property
  def tipo(self):
    return self.__tipo
  @tipo.setter
  def tipo(self, alteracao):
    raise ValueError(self.bloquear_modificacao("tipo"))

  @property
  def descricao(self):
    return self.__descricao
  @descricao.setter
  def descricao(self, alteracao):
    raise ValueError(self.bloquear_modificacao("descricao"))

  def exibirNotaFiscal(self):
    return print(f"""
      Código: {self.__codigo}
      Recebimento: {str(self.__recebimento)}
      Valor: R${self.__valor:.2f}
      Tipo: {self.__tipo}
      Descricao: {self.descricao}
      """)

NotaFiscal1 = NotaFiscal(
    352891032,
    date(2025, 8, 10),
    805.10,
    "Único",
    "Nota Fiscal de transação única."
    )

NotaFiscal1.exibirNotaFiscal()