# -*- coding: utf-8 -*-
"""classeUsuario

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJyEWyD28eLgtHzXahojl-LTfA1_se-_
"""

# usuário

class Usuario:
    def __init__(self, nome, email, senha, telefone, endereco, cpf):
        self.__nome = nome
        self.__email = email
        self.__senha = senha
        self.__telefone = telefone
        self.__endereco = endereco
        self.__cpf = cpf

    @property
    def nome(self):
        return self.__nome

    @nome.setter
    def nome(self, nome):
        self.__nome = nome

    @property
    def email(self):
        return self.__email

    @email.setter
    def email(self, email):
        self.__email = email

    @property
    def senha(self):
        return self.__senha

    @senha.setter
    def senha(self, senha):
        self.__senha = senha

    @property
    def telefone(self):
        return self.__telefone

    @telefone.setter
    def telefone(self, telefone):
        self.__telefone = telefone

    @property
    def endereco(self):
        return self.__endereco

    @endereco.setter
    def endereco(self, endereco):
        self.__endereco = endereco

    @property
    def cpf(self):
        return self.__cpf

    def excluirConta(self):
        self.nome = None
        self.email = None
        self.senha = None
        self.telefone = None
        self.endereco = None
        self.cpf = None
        print("Conta excluída com sucesso!")

    def mudarSeha(self):
        ns = input("Digite a nova senha: ")
        ns2 = input("Confirme a nova senha: ")
        if ns == ns2:
            self.senha = ns
            print("Senha alterada com sucesso!")
        else:
            print("As senhas não conferem!")

    def mudarEmail(self):
        ne = input("Digite o novo email: ")
        self.email = ne
        print("Email alterado com sucesso!")

    def mudarTelefone(self):
        nt = input("Digite o novo telefone: ")
        self.telefone = nt
        print("Telefone alterado com sucesso!")

    def mudarEndereco(self):
        ne = input("Digite o novo endereço: ")
        self.endereco = ne
        print("Endereço alterado com sucesso!")

    def mudarNome(self):
        nn = input("Digite o novo nome: ")
        self.nome = nn
        print("Nome alterado com sucesso!")